@startuml
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include FONTAWESOME/users.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

AddElementTag("target", $fontColor="#fff", $bgColor="#b35806")
skinparam linetype ortho

Person(storeCommunicationUser, "Medewerker winkelcommunicatie", "Verantwoordelijk voor relevante winkelcommunicatie")
Person(businessUser, "Hoofdkantoormedewerker", "Heeft communicatiebehoefte naar de winkels", "users")
Person(storeUser, "Winkelmedewerker", "Wil alleen relevante communicatie ontvangen" ,"users")

System_Boundary(communication, "Winkelcommunicatie") {
    Boundary(jumboEnv, "Jumbo", "Jumbo beheerde omgeving") {

        Boundary(sharePoint, "JumboNet", "SharePoint") {
            Container(storePage, "Winkelpagina", "Collectie van 1 pagina per winkel")
            Container(managementPage, "Winkelberichten beheer", "Beheerpagina voor het indienen van berichten")
        }

        Boundary(azure, "Azure", "Cloud") {
            Container_Ext(mdt, "MDT", "MDT microservice", $tags="target")
            Container(messageService, "Berichtenservice", "Verantwoordelijk voor het publiceren van winkelberichten")
            Container(MDTMessageService, "MDT Berichtenservice", "Verantwoordelijk voor het publiceren van MDT winkelberichten")
        }

        Container_Ext(ad, "Active Directory", "Beheer van autorisaties")
    }
}

Lay_L(storeCommunicationUser, businessUser)

'Lay_R(sharePoint, azure)

Rel(businessUser, managementPage, "Dient generieke berichten in")
Rel_D(storeCommunicationUser, managementPage, "Beoordeelt ingediende berichten")

Rel(storeCommunicationUser, mdt, "Creëert winkel specifieke berichten")
Rel(mdt, MDTMessageService, "gebruikt")
Rel(mdt, ad, "gebruikt")
Rel(MDTMessageService, storePage, "Publiceert bericht op de betreffende pagina")

Rel(storeUser, storePage, "ontvangt communicatie")

Rel(messageService, managementPage, "Haalt berichten op die gepubliceert moeten worden")
Rel(messageService, storePage, "Publiceert berichten op de betreffende pagina's")

Rel(sharePoint, ad, "Gebruikt")

'LAYOUT_LEFT_RIGHT()
SHOW_DYNAMIC_LEGEND()
@enduml
